### ISSUE TITLE
test_dataset is missing

### ISSUE THREAD

**Issue by ShaniaShan** [sycny/ZIP#1]
Thanks for sharing the wonderful work!

When I attempt to test the defense performance, it throws the following errors:

Traceback (most recent call last):
  File "/ZIP/main.py", line 177, in <module>
    sys.exit(main())
  File "/ZIP/main.py", line 171, in main
    purified_instance.train(schedule)
  File "/ZIP/attack/BackdoorBox/core/attacks/base.py", line 188, in train
    predict_digits, labels = self._cleantest(self.test_dataset, device, self.current_schedule['batch_size'], self.current_schedule['num_workers'])
  File "/ZIP/attack/BackdoorBox/core/attacks/base.py", line 405, in _cleantest
    predict_digits = torch.cat(predict_digits, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors

It seems that the test_dataset does not exist. According to your instructions, the Imagenette dataset has been in the correct directory. I successfully tested the attack performance. Thanks for any kind comments for addressing the issues.

**Comment by sycny** [comment]
Hi! Thanks for bringing this problem to our attention.

It did seem that the test_dataset is not included. Before we move further, could you confirm the following settings:

1. Could you confirm that you have downloaded the dataset from this [link](https://outlookuga-my.sharepoint.com/:u:/g/personal/ys07245_uga_edu/EXJdoUxODb5Grwacqwg7R00BvpL5eIITN2jXdN4cNDEURg?e=kxPmVO). And you have put the pre-purified images into the corresponding path (See Step 1 in "Prepare the attacked models and pre-purified images"). Only Imagenette datasets can not be verified in the current mode. 

2. Can you also please confirm you are using command lines provided [here](https://github.com/sycny/ZIP/tree/main?tab=readme-ov-file#test-the-defense-performance). For example, using:
```
python main.py --dataset Imagenette2 --attack_method BadNet -upctes -upptes --img_size 256 --deg Demo --at_threshold 1  --deg_scale 1.0 --img_size 256
```
